### ISSUE TITLE
 DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#410]
DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead

**Comment by RishiKumarRay** [comment]
I would like to do this

**Comment by RishiKumarRay** [comment]
Do we have to simply replace the module? Right

**Comment by cjkrolak** [comment]
sure, go for it.  You would have to compare the two function prototypes to see if it's a simple replace or not, the load_module() method is returning a python module, I haven't looked at the new function yet.
