### ISSUE TITLE
supervisor_flask_server not working through docker container

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#556]
IP address http://172.17.0.2:5001/ does not resolve

**Comment by SamirPS** [comment]
What was the command line to launch  the container ?

**Comment by cjkrolak** [comment]
to launch the container and launch the flask server: 

docker run --privileged --interactive cjkrolak/thermostatsupervisor:develop thermostatsupervisor.supervisor_flask_server -t=emulator -z=0 -p=180
